# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-04-18 07:19
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0004_backtracker_hiptracker_thightracker_userprofile_extended'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile_extended',
            name='gender',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='userprofile_extended',
            name='goal',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
    ]
