# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-04-18 09:18
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0005_auto_20160418_1249'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile_extended',
            name='gender',
            field=models.CharField(blank=True, choices=[('M', 'Male'), ('F', 'Female')], max_length=1, null=True),
        ),
    ]
