# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-04-18 16:28
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0007_auto_20160418_1500'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile_extended',
            name='age',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='userprofile_extended',
            name='mobile',
            field=models.IntegerField(blank=True, max_length=10, null=True),
        ),
    ]
