# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-04-18 17:19
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0008_auto_20160418_2158'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile_extended',
            name='age',
            field=models.IntegerField(blank=True, max_length=3, null=True),
        ),
    ]
