# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-04-27 17:15
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0009_auto_20160418_2249'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile_extended',
            name='image',
            field=models.FileField(blank=True, null=True, upload_to=''),
        ),
    ]
