# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-04-27 17:47
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0010_userprofile_extended_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile_extended',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
    ]
