# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-05-05 17:12
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0011_auto_20160427_2317'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile_extended',
            name='trainer',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
