# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-05-07 14:43
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0012_userprofile_extended_trainer'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile_extended',
            name='nutritionist',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
