# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-05-07 16:24
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0013_userprofile_extended_nutritionist'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile_extended',
            name='contact',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='userprofile_extended',
            name='supplimentexpert',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
