# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-05-07 17:16
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0014_auto_20160507_2154'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile_extended',
            name='about',
            field=models.CharField(blank=True, max_length=400, null=True),
        ),
    ]
