# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-05-08 16:28
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0017_photos'),
    ]

    operations = [
        migrations.AddField(
            model_name='photos',
            name='description',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
