# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-05-26 16:31
from __future__ import unicode_literals

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('tracker', '0018_photos_description'),
    ]

    operations = [
        migrations.CreateModel(
            name='subscription',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_name', models.CharField(blank=True, max_length=100, null=True)),
                ('subscription_startdate', models.DateTimeField(blank=True, default=datetime.datetime(2016, 5, 26, 22, 1, 24, 471633))),
                ('expire_days', models.IntegerField(blank=True, max_length=5, null=True)),
                ('subscription_status', models.BooleanField()),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AlterField(
            model_name='photos',
            name='description',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='userprofile_extended',
            name='contact',
            field=models.IntegerField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='userprofile_extended',
            name='image',
            field=models.ImageField(blank=True, default='./avatar.png', null=True, upload_to=''),
        ),
    ]
