# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-07-01 17:53
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0020_auto_20160623_2315'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile_extended',
            name='height',
            field=models.FloatField(blank=True, max_length=3, null=True),
        ),
        migrations.AlterField(
            model_name='subscription',
            name='subscription_startdate',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2016, 7, 1, 23, 23, 0, 825349)),
        ),
    ]
